# PATHS
experiment_path: '/home/npoleksic/LSS/ncb-core/users/npoleksic/sarah_data_new_hpc' # absolute path to the experimental data folder
raw_data_path: 'cfos/16-09-36_TR1 640_UltraII_C00_xyz-Table Z<Z,4>.ome.tif' # relative path to the raw data from the experimental data folder
autof_data_path: 'autof/15-12-07_TR1 autofluo_UltraII_C00_xyz-Table Z<Z,4>.ome.tif' # relative path to autofluorescence data from the experimental data folder 
# NOTE: generalize image file names with tag (i.e. Z<Z,4> instead of Z0001, Z0002, etc.)

# RESOLUTION
raw_x_resolution: 3.77556 # resolution of the raw data in the x-direction
raw_y_resolution: 3.77556 # resolution of the raw data in the y-direction
raw_z_resolution: 3 # resolution of the raw data in the z-direction
autof_x_resolution: 3.77556 # resolution of the autofluorescence data in the x-direction
autof_y_resolution: 3.77556 # resolution of the autofluorescence data in the y-direction
autof_z_resolution: 3 # resolution of the autofluorescence data in the z-direction

# ATLAS SETUP
# NOTE: to improve performance, ensure the following parameters closely align with the experimental data
x_orientation: 3 # atlas axis that matches experimental data x-axis
y_orientation: 1 # atlas axis that matches experimental data y-axis
z_orientation: 2 # atlas axis that matches experimental data z-axis
# NOTE: orientations should be expressed as a 1, 2, or 3 corresponding to axes x, y, and z
atlas_x_min: 0 # minimum crop in x-direction (after atlas-matching)
atlas_x_max: 'MAX' # maximum crop in x-direction
atlas_y_min: 0 # minimum crop in y-direction
atlas_y_max: 'MAX' # maximum crop in y-direction
atlas_z_min: 100 # minimum crop in z-direction
atlas_z_max: 326 # maximum crop in z-direction

# MISC
filter_size_min: 20 # minimum cell size to be counted
filter_size_max: 900 # maximum cell size to be counted
include_checkpoints: false # check progress during execution

# illumination_correction: false
# illumination_background: -1
# illumination_scaling: -1
# illumination_save: false
# background_removal: false
# background_shape: false
# background_form: false
# background_save: false
# equalization: false
# equalization_percentile: false
# equalization_max: false
# equalization_selem: false
# equalization_spacing: false
# equalization_interpolate: false
# equalization_save: false
# dog: false
# dog_shape: false
# dog_sigma: false
# dog_sigma2: false
# dog_save: false
# maxima_detection: false
# maxima_hmax: false
# maxima_shape: false
# maxima_threshold: false
# maxima_save: false
# shape_detection: false
# shape_threshold: false
# shape_save: false
# intensity_detection: false
# intensity_method: false
# intensity_shape: false
# intensity_measure: false
# intensity_save: false
